#!/usr/bin/env bash
# Stage the vendor display-service APKs + their licence notices for the
# with-services (cnsdk) build of the Android installer.
#
#   stage-cnsdk.sh --tag v0.10.69 --apks <dir> --licenses <dir> --out <staging>
#   ./gradlew :app:assembleCnsdkDebug -PcnsdkStagingDir=<staging>
#
# <dir> for --apks holds device-service-release-*.apk and headTracking-service-release-*.apk,
# exactly as `gh release download <tag> -R LeiaInc/CNSDK` leaves them (and as
# apks/1-cnsdk-services/ of a tablet bundle holds them). --licenses holds the CNSDK
# release's LICENSE.txt, LICENSE-3RD-PARTY.txt and the upstream AUTHORS notices.
#
# Why a script and not a hand-written index: package, versionName and versionCode are
# READ OUT of each APK with aapt2, and the sha256 is computed from the bytes that get
# embedded. A hand-typed digest in this repo has false-passed before; an index derived
# from the artifact cannot disagree with it. The app re-hashes each APK against this
# index before installing it.
#
# The output never goes anywhere near git: it is private vendor code. Point --out at a
# scratch directory.
set -euo pipefail

TAG="" APKS="" LICS="" OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --tag) TAG=$2; shift 2 ;;
    --apks) APKS=$2; shift 2 ;;
    --licenses) LICS=$2; shift 2 ;;
    --out) OUT=$2; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$TAG" ] && [ -n "$APKS" ] && [ -n "$LICS" ] && [ -n "$OUT" ] || {
  echo "usage: $0 --tag <cnsdk_services tag> --apks <dir> --licenses <dir> --out <staging>" >&2; exit 2; }

die() { echo "stage-cnsdk: $*" >&2; exit 1; }

# aapt2: $AAPT2, else the newest build-tools under ANDROID_HOME / ANDROID_SDK_ROOT / the
# macOS default SDK location.
if [ -z "${AAPT2:-}" ]; then
  for sdk in "${ANDROID_HOME:-}" "${ANDROID_SDK_ROOT:-}" "$HOME/Library/Android/sdk" /usr/local/lib/android/sdk; do
    [ -n "$sdk" ] || continue
    c=$(ls -d "$sdk"/build-tools/*/aapt2 2>/dev/null | sort -V | tail -1 || true)
    [ -n "$c" ] && { AAPT2=$c; break; }
  done
fi
[ -n "${AAPT2:-}" ] && [ -x "$AAPT2" ] || die "aapt2 not found (set AAPT2 or ANDROID_HOME)"

if command -v sha256sum >/dev/null; then sha() { sha256sum "$1" | cut -d' ' -f1; }
else sha() { shasum -a 256 "$1" | cut -d' ' -f1; }; fi

# Exactly one of each. Two matches is not "pick one": it is a directory holding two
# vendor builds, and which one ships would be decided by sort order.
one() {
  local n; n=$(ls -1 "$APKS"/$1 2>/dev/null | wc -l | tr -d ' ')
  [ "$n" = 1 ] || die "expected exactly one $1 in $APKS, found $n"
  ls -1 "$APKS"/$1
}
DS=$(one 'device-service-release-*.apk')
# Capital T is load-bearing: the release asset names are case-sensitive.
HT=$(one 'headTracking-service-release-*.apk')

rm -rf "$OUT/cnsdk"
mkdir -p "$OUT/cnsdk/apks" "$OUT/cnsdk/licenses"

{
  echo "# GENERATED by android-installer/scripts/stage-cnsdk.sh — do not hand-edit."
  echo "# record<TAB>fields...   apk: file package versionName versionCode sha256 size"
  printf 'tag\t%s\n' "$TAG"
} > "$OUT/cnsdk/index.tsv"

# The package each file MUST be. A device-service file that is not the display-config
# package is a mislabelled asset, and installing it under that row would be a lie.
for pair in "$DS|com.leialoft.display.config" "$HT|com.leia.headtrackingservice"; do
  f=${pair%%|*}; want=${pair##*|}
  badge=$("$AAPT2" dump badging "$f" 2>/dev/null | grep -m1 '^package: ' || true)
  pkg=$(printf '%s' "$badge" | sed -nE "s/.* name='([^']*)'.*/\1/p")
  code=$(printf '%s' "$badge" | sed -nE "s/.* versionCode='([^']*)'.*/\1/p")
  name=$(printf '%s' "$badge" | sed -nE "s/.* versionName='([^']*)'.*/\1/p")
  [ "$pkg" = "$want" ] || die "$(basename "$f") is package '$pkg', expected $want"
  [ -n "$code" ] && [ -n "$name" ] || die "could not read versionCode/versionName from $(basename "$f")"
  # The tag is v0.10.69; the services report 0.10.69. A carried build that is not the
  # pinned release is the wrong build, whatever its file name says.
  [ "$name" = "${TAG#v}" ] || die "$(basename "$f") reports versionName $name, but the pin is $TAG"
  cp "$f" "$OUT/cnsdk/apks/"
  b=$(basename "$f")
  printf 'apk\t%s\t%s\t%s\t%s\t%s\t%s\n' "$b" "$pkg" "$name" "$code" \
    "$(sha "$OUT/cnsdk/apks/$b")" "$(wc -c < "$OUT/cnsdk/apks/$b" | tr -d ' ')" >> "$OUT/cnsdk/index.tsv"
done

# LICENSE-3RD-PARTY.txt: libleiaCore-impl.so statically links libzmq under a modified
# LGPLv3 whose static-link exception still requires the licence text and copyright
# notice to ACCOMPANY the binary; Eigen (MPL-2.0) and the Apache-2.0 components need
# their notices to travel too. An installer that embeds the binaries is a distribution
# of them, exactly as the bundle zip is — so the same four files, and the same refusal.
for l in LICENSE.txt LICENSE-3RD-PARTY.txt ZMQ.AUTHORS.txt SIMDJSON.AUTHORS.txt; do
  [ -s "$LICS/$l" ] || die "$LICS/$l is missing — refusing to embed LGPL/MPL/Apache binaries without their notices"
  cp "$LICS/$l" "$OUT/cnsdk/licenses/"
  printf 'license\t%s\n' "$l" >> "$OUT/cnsdk/index.tsv"
done

echo "staged CNSDK $TAG into $OUT/cnsdk:"
cat "$OUT/cnsdk/index.tsv"
