package com.displayxr.installer

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.ByteArrayInputStream
import java.io.File
import java.security.MessageDigest

/**
 * The with-services build: its index, its install order, and the version verdicts.
 *
 * The fixture rows are the REAL values `aapt2 dump badging` reads from the pinned
 * CNSDK v0.10.69 service APKs (the digests are placeholders; the parser only checks
 * their shape). Note the two versionCodes differ in their leading digits —
 * 290010069 vs 300010069 — which is why nothing here compares one service's code
 * against the other's.
 */
class EmbeddedServicesTest {

    private val dsSha = "a".repeat(64)
    private val htSha = "b".repeat(64)

    private fun index(
        apkLines: List<String> = listOf(
            // Deliberately head tracking FIRST: the order in the file must not matter.
            "apk\theadTracking-service-release-0.10.69+193.8291a2e.apk\tcom.leia.headtrackingservice\t0.10.69\t300010069\t$htSha\t46521652",
            "apk\tdevice-service-release-0.10.69+193.8291a2e.apk\tcom.leialoft.display.config\t0.10.69\t290010069\t$dsSha\t13888346",
        ),
        licenses: List<String> = listOf("LICENSE.txt", "LICENSE-3RD-PARTY.txt", "ZMQ.AUTHORS.txt"),
        tag: String? = "v0.10.69",
    ): String = buildString {
        appendLine("# GENERATED by android-installer/scripts/stage-cnsdk.sh")
        tag?.let { appendLine("tag\t$it") }
        apkLines.forEach { appendLine(it) }
        licenses.forEach { appendLine("license\t$it") }
    }

    private fun rejects(text: String, containing: String) {
        try {
            EmbeddedServices.parseIndex(text)
            fail("expected the index to be rejected ($containing)")
        } catch (e: EmbeddedIndexException) {
            assertTrue("message was: ${e.message}", e.message!!.contains(containing))
        }
    }

    // ---- ordering ------------------------------------------------------------

    @Test
    fun `device-service is installed first whatever order the index lists them in`() {
        val b = EmbeddedServices.parseIndex(index())
        assertEquals("v0.10.69", b.tag)
        assertEquals(
            listOf("com.leialoft.display.config", "com.leia.headtrackingservice"),
            b.services.map { it.packageName },
        )
        assertEquals(290010069L, b.services[0].versionCode)
        assertEquals("cnsdk/apks/device-service-release-0.10.69+193.8291a2e.apk", b.services[0].assetPath)
    }

    @Test
    fun `services come before the runtime, and the standard build is unchanged`() {
        val b = EmbeddedServices.parseIndex(index())
        val ids = Catalog.components(b).map { it.id }
        assertEquals(
            listOf("service:com.leialoft.display.config", "service:com.leia.headtrackingservice", "runtime"),
            ids.take(3),
        )
        assertEquals(Catalog.COMPONENTS, Catalog.components(null))
        assertTrue(Catalog.components(b).drop(2).all { it.embedded == null })
    }

    @Test
    fun `row ids and package names stay distinct once services are added`() {
        val all = Catalog.components(EmbeddedServices.parseIndex(index()))
        assertEquals(all.size, all.map { it.id }.toSet().size)
        assertEquals(all.size, all.map { it.packageName }.toSet().size)
    }

    // ---- what the index may not do -------------------------------------------

    @Test
    fun `an index with only one of the two services is rejected, not half-installed`() {
        rejects(index(apkLines = listOf(index().lines().first { it.contains("display.config") })), "com.leia.headtrackingservice")
    }

    @Test
    fun `an index naming any other package is rejected`() {
        val extra = "apk\tevil.apk\tcom.example.evil\t1.0\t1\t$dsSha\t10"
        rejects(index(apkLines = index().lines().filter { it.startsWith("apk") } + extra), "com.example.evil")
    }

    @Test
    fun `a package listed twice is rejected`() {
        val ds = index().lines().first { it.contains("display.config") }
        rejects(index(apkLines = index().lines().filter { it.startsWith("apk") } + ds), "twice")
    }

    @Test
    fun `the licence notices are mandatory`() {
        rejects(index(licenses = listOf("LICENSE.txt")), "LICENSE-3RD-PARTY.txt")
        rejects(index(licenses = emptyList()), "LICENSE.txt")
    }

    @Test
    fun `malformed records are rejected with the line they are on`() {
        rejects(index(tag = null), "no tag")
        rejects(index() + "tag\tv0.10.70\n", "more than one tag")
        rejects(index() + "surprise\tx\n", "unknown record")
        val shortDigest = index().replace(dsSha, "abc")
        rejects(shortDigest, "sha256")
        val badCode = index().replace("290010069", "twelve")
        rejects(badCode, "versionCode")
        val pathy = index().replace("device-service-release", "../device-service-release")
        rejects(pathy, "bad file name")
    }

    @Test
    fun `comments, blank lines and CRLF are tolerated`() {
        val crlf = index().replace("\n", "\r\n") + "\r\n# trailing comment\r\n"
        assertEquals(2, EmbeddedServices.parseIndex(crlf).services.size)
    }

    // ---- the verifying copy ----------------------------------------------------

    private fun apkFor(bytes: ByteArray) = EmbeddedApk(
        fileName = "x.apk",
        packageName = "com.leialoft.display.config",
        versionName = "0.10.69",
        versionCode = 290010069,
        sha256 = MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) },
        size = bytes.size.toLong(),
    )

    @Test
    fun `an intact asset is copied out byte for byte`() {
        val bytes = ByteArray(700_000) { (it * 31).toByte() }
        val dest = File.createTempFile("embedded", ".apk")
        EmbeddedServices.copyVerified(ByteArrayInputStream(bytes), dest, apkFor(bytes))
        assertTrue(dest.readBytes().contentEquals(bytes))
        dest.delete()
    }

    @Test
    fun `a truncated or altered asset is refused and the partial copy deleted`() {
        val bytes = ByteArray(10_000) { it.toByte() }
        val apk = apkFor(bytes)
        val dest = File.createTempFile("embedded", ".apk")
        try {
            EmbeddedServices.copyVerified(ByteArrayInputStream(bytes.copyOf(9_000)), dest, apk)
            fail("a truncated asset must not be handed to the package installer")
        } catch (e: EmbeddedIndexException) {
            assertTrue(e.message!!.contains("nothing was installed"))
        }
        assertFalse(dest.exists())

        val altered = bytes.copyOf().also { it[5] = 99 }
        try {
            EmbeddedServices.copyVerified(ByteArrayInputStream(altered), dest, apk)
            fail("an altered asset must not be handed to the package installer")
        } catch (e: EmbeddedIndexException) {
            // expected
        }
        assertFalse(dest.exists())
    }
}

/**
 * Installed-vs-carried for the display services. "Newer" is claimed only on
 * Android's own downgrade rule (versionCode), never on a versionName.
 */
class ServicePlannedStatusTest {

    private val carried = EmbeddedApk(
        fileName = "device-service-release-0.10.69+193.8291a2e.apk",
        packageName = "com.leialoft.display.config",
        versionName = "0.10.69",
        versionCode = 290010069,
        sha256 = "a".repeat(64),
        size = 1,
    )

    @Test
    fun `absent is an install`() {
        assertEquals(RowStatus.INSTALL, servicePlannedStatus(Installed.Absent, carried))
    }

    @Test
    fun `the factory build is an update`() {
        // NP02J factory device-service; Lume Pad 2 factory is 0.8.20.
        assertEquals(RowStatus.UPDATE, servicePlannedStatus(Installed.Exact("0.8.29", 290008029), carried))
        assertEquals(RowStatus.UPDATE, servicePlannedStatus(Installed.Exact("0.10.68", 290010068), carried))
    }

    @Test
    fun `the carried build already installed is up to date`() {
        assertEquals(RowStatus.UP_TO_DATE, servicePlannedStatus(Installed.Exact("0.10.69", 290010069), carried))
    }

    @Test
    fun `a higher versionCode is newer, because that is exactly what Android refuses`() {
        assertEquals(RowStatus.NEWER_INSTALLED, servicePlannedStatus(Installed.Exact("0.10.70", 290010070), carried))
    }

    /**
     * The README rule: no verdict with consequences on a comparison the code
     * cannot make. A versionName that SORTS higher but a versionCode that is
     * lower is an update by Android's rules — the name is not what decides.
     */
    @Test
    fun `versionName never decides newer`() {
        assertEquals(RowStatus.UPDATE, servicePlannedStatus(Installed.Exact("9.9.9", 290010000), carried))
        // No readable versionCode: offered for install, never "newer".
        val noCode = servicePlannedStatus(Installed.Exact("9.9.9", null), carried)
        assertNotEquals(RowStatus.NEWER_INSTALLED, noCode)
        assertEquals(RowStatus.UPDATE_UNVERIFIABLE, noCode)
        assertEquals(RowStatus.UP_TO_DATE, servicePlannedStatus(Installed.Exact("0.10.69", null), carried))
    }

    @Test
    fun `same versionCode with a different name is offered, not asserted`() {
        val s = servicePlannedStatus(Installed.Exact("0.10.69-dev", 290010069), carried)
        assertEquals(RowStatus.UPDATE_UNVERIFIABLE, s)
        assertTrue(s in PLANNED_STATUSES)
    }
}
